apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kv-store
  template:
    metadata:
      labels:
        app: kv-store
    spec:
      containers:
      - name: kv-store
        image: kv-store:latest
        ports:
        - containerPort: 4000
        env:
        - name: SECRET_KEY_BASE
          value: pippo
